In [3]:
import pandas as pd 
import numpy as np

In [27]:
df = pd.read_csv("../data/raw/climate_data.csv")
df.head()

,Year,Country,Avg Temperature (°C),CO2 Emissions (Tons/Capita),Sea Level Rise (mm),Rainfall (mm),Population,Renewable Energy (%),Extreme Weather Events,Forest Area (%)
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         1000 non-null   int64
 1   Country                      1000 non-null   object
 2   Avg Temperature (°C)         1000 non-null   float64
 3   CO2 Emissions (Tons/Capita)  1000 non-null   float64
 4   Sea Level Rise (mm)          1000 non-null   float64
 5   Rainfall (mm)                1000 non-null   int64
 6   Population                   1000 non-null   int64
 7   Renewable Energy (%)         1000 non-null   float64
 8   Extreme Weather Events       1000 non-null   int64
 9   Forest Area (%)              1000 non-null   float64
dtypes: float64(5), int64(4), object(1)
memory usage: 78.3+ KB

In [28]:
# kolon isimlerini temizledim 
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("(", "").str.replace(")", "").str.replace("%","").str.replace("/","_")

df.head()

,year,country,avg_temperature_°c,co2_emissions_tons_capita,sea_level_rise_mm,rainfall_mm,population,renewable_energy_,extreme_weather_events,forest_area_
0,2006,UK,8.9,9.3,3.1,1441,530911230,20.4,14,59.8
1,2019,USA,31.0,4.8,4.2,2407,107364344,49.2,8,31.0
2,2014,France,33.9,2.8,2.2,1241,441101758,33.3,9,35.5
3,2010,Argentina,5.9,1.8,3.2,1892,1069669579,23.7,7,17.7
4,2007,Germany,26.9,5.6,2.4,1743,124079175,12.5,4,17.4

In [29]:
df["country"] = df["country"].str.strip()

In [10]:
df["country"]

0             UK
1            USA
2         France
3      Argentina
4        Germany
         ...
995        India
996           UK
997    Argentina
998    Australia
999      Germany
Name: country, Length: 1000, dtype: object

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,1000.0,2.011432e+03,7.147199e+00,2000.0,2.005000e+03,2.012000e+03,2.018000e+03,2.023000e+03
avg_temperature_°c,1000.0,1.988310e+01,8.542897e+00,5.0,1.217500e+01,2.010000e+01,2.722500e+01,3.490000e+01
co2_emissions_tons_capita,1000.0,1.042580e+01,5.614665e+00,0.5,5.575000e+00,1.070000e+01,1.540000e+01,2.000000e+01
sea_level_rise_mm,1000.0,3.009600e+00,1.146081e+00,1.0,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
rainfall_mm,1000.0,1.738761e+03,7.089766e+02,501.0,1.098750e+03,1.726000e+03,2.362500e+03,2.999000e+03
population,1000.0,7.053830e+08,4.093910e+08,3660891.0,3.436242e+08,7.131166e+08,1.073868e+09,1.397016e+09
renewable_energy_,1000.0,2.730050e+01,1.297081e+01,5.1,1.610000e+01,2.715000e+01,3.892500e+01,5.000000e+01
extreme_weather_events,1000.0,7.291000e+00,4.422655e+00,0.0,3.000000e+00,8.000000e+00,1.100000e+01,1.400000e+01
forest_area_,1000.0,4.057200e+01,1.739900e+01,10.1,2.560000e+01,4.115000e+01,5.580000e+01,7.000000e+01

In [13]:
#standartlastırma

In [18]:
numeric_cols = [
    "avg_temperature_°c",
    "co2_emissions_tons_capita",
    "sea_level_rise_mm",
    "rainfall_mm",
    "population",
    "renewable_energy_",
    "extreme_weather_events",
    "forest_area_"
]

In [19]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

,year,country,avg_temperature_°c,co2_emissions_tons_capita,sea_level_rise_mm,rainfall_mm,population,renewable_energy_,extreme_weather_events,forest_area_
0,2006,UK,0.130435,0.451282,0.525,0.376301,0.378403,0.340757,1.000000,0.829716
1,2019,USA,0.869565,0.220513,0.800,0.763010,0.074427,0.982183,0.571429,0.348915
2,2014,France,0.966555,0.117949,0.300,0.296237,0.313948,0.628062,0.642857,0.424040
3,2010,Argentina,0.030100,0.066667,0.550,0.556845,0.765066,0.414254,0.500000,0.126878
4,2007,Germany,0.732441,0.261538,0.350,0.497198,0.086423,0.164811,0.285714,0.121870

In [17]:
df.columns.tolist()

['year',
 'country',
 'avg_temperature_°c',
 'co2_emissions_tons_capita',
 'sea_level_rise_mm',
 'rainfall_mm',
 'population',
 'renewable_energy_',
 'extreme_weather_events',
 'forest_area_']

In [20]:
df.to_csv("../data/clean/climate_data_clean.csv", index=False)

In [22]:
dff = pd.read_csv("../data/clean/climate_data_clean.csv")
dff.head()

,year,country,avg_temperature_°c,co2_emissions_tons_capita,sea_level_rise_mm,rainfall_mm,population,renewable_energy_,extreme_weather_events,forest_area_
0,2006,UK,0.130435,0.451282,0.525,0.376301,0.378403,0.340757,1.000000,0.829716
1,2019,USA,0.869565,0.220513,0.800,0.763010,0.074427,0.982183,0.571429,0.348915
2,2014,France,0.966555,0.117949,0.300,0.296237,0.313948,0.628062,0.642857,0.424040
3,2010,Argentina,0.030100,0.066667,0.550,0.556845,0.765066,0.414254,0.500000,0.126878
4,2007,Germany,0.732441,0.261538,0.350,0.497198,0.086423,0.164811,0.285714,0.121870

In [23]:
dff.describe().T

,count,mean,std,min,25%,50%,75%,max
year,1000.0,2011.432000,7.147199,2000.0,2005.000000,2012.000000,2018.000000,2023.0
avg_temperature_°c,1000.0,0.497763,0.285716,0.0,0.239967,0.505017,0.743311,1.0
co2_emissions_tons_capita,1000.0,0.509015,0.287932,0.0,0.260256,0.523077,0.764103,1.0
sea_level_rise_mm,1000.0,0.502400,0.286520,0.0,0.250000,0.500000,0.750000,1.0
rainfall_mm,1000.0,0.495501,0.283818,0.0,0.239291,0.490392,0.745196,1.0
population,1000.0,0.503620,0.293817,0.0,0.243989,0.509171,0.768079,1.0
renewable_energy_,1000.0,0.494443,0.288882,0.0,0.244989,0.491091,0.753341,1.0
extreme_weather_events,1000.0,0.520786,0.315904,0.0,0.214286,0.571429,0.785714,1.0
forest_area_,1000.0,0.508715,0.290467,0.0,0.258765,0.518364,0.762938,1.0

### 
Veri Kümesi Başlığı:
Küresel İklim Değişikliği Göstergeleri: Kapsamlı Bir Veri Kümesi (2000-2024)

Alt başlık:
Ülkeler genelinde sıcaklık, emisyonlar, deniz seviyesi yükselmesi ve çevresel eğilimlerin takibi

Açıklama:
Bu veri seti, 2000 ile 2024 yılları arasında farklı ülkelerden toplanan temel iklim değişikliği göstergelerine ilişkin kapsamlı bir genel bakış sunmaktadır. İklim değişikliğinin küresel etkisini yansıtan çeşitli çevresel ve sosyo-ekonomik faktörleri yakalayan 1000 veri noktası içermektedir. Veri seti, ortalama sıcaklık, CO2 emisyonları, deniz seviyesi yükselmesi, yağış düzenleri ve daha fazlasına odaklanarak kullanıcıların eğilimleri, korelasyonları ve anormallikleri analiz etmelerini sağlamaktadır.

Alan Açıklaması:
Yıl:
Verilerin kaydedildiği yıl, 2000 ile 2024 yılları arasındadır. İklim değişikliği ve ilgili değişkenlerdeki tarihsel eğilimleri zaman içinde izlemeye yardımcı olur.

Ülke:
İklim verilerinin toplandığı ülke veya bölge. Veri seti, dünyanın dört bir yanından farklı coğrafi bölgeleri ve iklimleri temsil eden çeşitli ülkeleri içermektedir.

Ortalama Sıcaklık (°C):
Her ülkede kaydedilen yıllık ortalama sıcaklık, santigrat derece cinsinden ölçülür. Bu alan, bölgeler ve zaman içindeki sıcaklık değişimlerinin karşılaştırılmasına olanak tanır.

CO2 Emisyonları (Kişi Başına Metrik Ton):
Ülkenin sera gazlarına katkısını yansıtan, kişi başına düşen ortalama CO2 emisyonu miktarı (metrik ton cinsinden). Bu alan, insan faaliyetleri ile çevresel değişiklikler arasındaki bağlantıyı analiz etmek için faydalıdır.

Deniz Seviyesi Yükselmesi (mm):
Kıyı bölgeleri için kaydedilen yıllık deniz seviyesi yükselişi (milimetre cinsinden). Bu gösterge, küresel ısınmanın buzulların erimesi ve deniz suyunun termal genleşmesi üzerindeki etkisini yansıtır ve kıyı nüfusu üzerindeki etkilerin incelenmesi için kritik öneme sahiptir.

Yağış (mm):
Yıllık toplam yağış miktarı milimetre cinsinden kaydedilir. Bu alan, kuraklıkları, selleri ve su kaynakları yönetimini anlamak için gerekli olan değişen yağış modellerini vurgular.

Nüfus:
Belirtilen yılda ülkenin nüfusu. Nüfus verileri, emisyonları veya kişi başına düşen diğer analizleri normalleştirmek ve insanlığın çevre üzerindeki etkisini anlamak için önemlidir.

Yenilenebilir Enerji (%):
Bir ülkenin toplam enerji tüketiminin yenilenebilir enerji kaynaklarından (güneş, rüzgar, hidroelektrik vb.) karşılanan yüzdesi. Bu ölçüt, sürdürülebilir enerjiye doğru kaydedilen ilerlemeyi değerlendirmek ve fosil yakıtlara olan bağımlılığı azaltmak için hayati önem taşımaktadır.

Aşırı Hava Olayları:
Her ülkede kaydedilen aşırı hava olaylarının sayısı; örneğin kasırgalar, seller, orman yangınları ve kuraklıklar. Bu olayların takibi, iklim değişikliğindeki artışı doğal afetlerin sıklığıyla ilişkilendirmeye yardımcı olur.

Orman Alanı (%):
Bir ülkenin toplam kara alanının ormanlarla kaplı yüzdesi. Orman örtüsü, biyoçeşitlilik ve karbon tutulumu açısından kritik bir göstergedir ve azalmalar genellikle ormansızlaşma ve habitat kaybıyla ilişkilendirilir.

Uygulama Alanları:
İklim Araştırmaları:
Bu veri seti, küresel iklim değişikliği eğilimlerini inceleyen araştırmacılar ve analistler için paha biçilmezdir. Kullanıcılar, birden fazla göstergeye odaklanarak sıcaklık değişimleri, emisyonlar, ormansızlaşma ve aşırı hava olayları arasındaki ilişkileri değerlendirebilirler.

Çevre Politikası Oluşturma:
Hükümetler ve politika analistleri, bu veri setini kullanarak tarihsel ve bölgesel verilere dayalı daha etkili iklim politikaları geliştirebilirler. Örneğin, ülkeler emisyon verilerini kullanarak uluslararası anlaşmalara uygun gerçekçi azaltma hedefleri belirleyebilirler.

Yenilenebilir Enerji Çalışmaları:
Yenilenebilir enerji verileri, farklı bölgelerin daha yeşil enerji kaynaklarına geçişini anlamamıza yardımcı olur ve yüksek emisyonlu ve düşük emisyonlu ülkeler arasında karşılaştırma imkanı sunar.

Tahmin Modellemesi:
Veriler, özellikle küresel sıcaklık artışı, deniz seviyesi değişiklikleri ve aşırı hava olaylarıyla ilgili olarak gelecekteki iklim senaryolarını tahmin etmek için makine öğrenimi modellerinde kullanılabilir.

Kamuoyu Bilgilendirme ve Eğitim:
Bu veri seti, iklim değişikliğinin etkileri konusunda farkındalık yaratmak için faydalı bir eğitim aracıdır. Öğrenciler ve genel halk, gerçek dünya verilerini incelemek ve sürdürülebilir kalkınmanın önemini öğrenmek için bu veri setini kullanabilir.

###

Şehirlerin iklimle ilgili göstergelerini (sıcaklık, CO₂ emisyonu, deniz seviyesi artışı vb.) analiz ederek iklim risk skorunu hesaplayan ve karar vericilere riskli bölgeleri gösteren bir karar destek sistemi geliştirmek.

In [24]:
dff

,year,country,avg_temperature_°c,co2_emissions_tons_capita,sea_level_rise_mm,rainfall_mm,population,renewable_energy_,extreme_weather_events,forest_area_
0,2006,UK,0.130435,0.451282,0.525,0.376301,0.378403,0.340757,1.000000,0.829716
1,2019,USA,0.869565,0.220513,0.800,0.763010,0.074427,0.982183,0.571429,0.348915
2,2014,France,0.966555,0.117949,0.300,0.296237,0.313948,0.628062,0.642857,0.424040
3,2010,Argentina,0.030100,0.066667,0.550,0.556845,0.765066,0.414254,0.500000,0.126878
4,2007,Germany,0.732441,0.261538,0.350,0.497198,0.086423,0.164811,0.285714,0.121870
...,...,...,...,...,...,...,...,...,...,...
995,2019,India,0.622074,0.384615,0.050,0.345877,0.972013,0.109131,0.571429,0.168614
996,2000,UK,0.561873,0.487179,0.300,0.309047,0.626159,0.218263,1.000000,0.333890
997,2019,Argentina,0.628763,0.430769,0.925,0.156125,0.801571,0.463252,0.714286,0.607679
998,2016,Australia,0.535117,0.738462,0.525,0.254203,0.270571,0.432071,0.214286,0.574290
999,2011,Germany,0.638796,0.861538,0.275,0.941954,0.283306,0.799555,0.214286,0.161937

bu veri setini hangi kararları almak için kullanırız ?   ve kpıler olusturulmalı

iklim riski yüksek bölgelerde yatırım kararları , çevre politikaları , yenilenebilir enerji yatırımları ...

kpı kısmında : ortalama sıcaklık , ortalama karbon emisyonu , ortalama deniz seviyesi , ortalama orman alanları , hava olayları , kişi başına düşen karbon emisyonu

2 tane uyarı : eğer bir ülkede kişi başına düşen karbon emisyonu çok yüksekse uyaracak , 
ülkede aşırı hava olayları varsa sistem uyarı versin 
düşük orman alanı uyarısı 
aşırı sıcak ise uyarı ...